%YAML:1.0
Camera.model: "pinhole" # "pinhole" 或 "fisheye"
Camera.width: 1920
Camera.height: 1080

CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1364.45, 0.0, 958.327, 
            0.0, 1366.46, 535.074, 
            0.0, 0.0, 1.0]

# 畸变系数
# (k1, k2, p1, p2, k3) 对于 pinhole 模型
# (k1, k2, k3, k4) 对于 fisheye 模型
DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [0.0958277, -0.198233, -0.000147133, -0.000430056, 0.000000]